version: "3.9"
services:
    web:
        container_name: ecommerce
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "8080:80"
        volumes:
            - ..:/usr/share/nginx/html
            - ./nginx:/var/log/nginx
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        working_dir: /usr/share/nginx/html
        networks:
            - db_default
networks:
    db_default:
        external: true
